### PR TITLE
Adds a blog article about png2webp

### PR DESCRIPTION
**Pull request by ribalba**
Not 100% finished but ready for the first read. 

@MichelleGruene FYI what is coming up

### CODE REVIEW

**Comment by ArneTR** [comment]
Nice one!

Two remarks:
- Can you link the wordpress that you have looked at? I think you just used the standard current download. But please link it with the exact version in case someone in one year wants to reproduce it or falsify it
- I would add a opinionated statement at the end to make the relevance to Green Coding as such:
> Although image compression is no new technique we see an important differnce here between classical perfomance engineering techniques and the newer spin on the topic, *Green Coding*, which we want to push forward.
For a normal website, even for wordpress, the transfer time is often *good enough* as the user does not even notice the latency on a normal connection. However we saved by just using a simple one time operation about 70% of transfer volume through the network. This means that in the near future some network switches do not have to be upgraded and we save hardware and thus CO2 for the plant. This is just a minor example of what we also consider Green Coding: Applying already known techniques for savings that are not performance critical, just to do reduce ressource consumption and thus CO2 emission.

**Comment by ArneTR** [comment]
Can you also add two things:
- How to make IE supported through a polyfill (has to be researched).
- Make an example for the IE hack: `<!--[if IE]><script src="/polyfill.js"></script><![endif]-->`
- Show the supported state via: https://caniuse.com/webp

**Comment by ribalba** [comment]
@ArneTR updated.

**Comment by ArneTR** [comment]
go from my site. Please check with @MichelleGruene when to best release it and if she has remarks

**Pull request merged**
